# Generated by Django 5.0.6 on 2024-06-21 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_names', models.CharField(choices=[('MS', 'marutisizuki'), ('NA', 'nano'), ('TA', 'tata')], max_length=2)),
                ('user_name', models.CharField(max_length=100)),
                ('ph_no', models.IntegerField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
