# Generated by Django 5.0.6 on 2024-06-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='ph_no',
        ),
    ]
