# Generated by Django 5.0.6 on 2024-06-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelstester', '0002_courses_alter_card_details_url_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('courses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelstester.courses', verbose_name='courses')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelstester.student', verbose_name='teacahers')),
            ],
        ),
    ]
