# Generated by Django 5.0.6 on 2024-06-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelstester', '0004_remove_teacher_courses_remove_teacher_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
