# Generated by Django 5.0.6 on 2024-06-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelstester', '0007_alter_teacher_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
    ]
