# Generated by Django 5.0.6 on 2024-06-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelstester', '0008_remove_teacher_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='students',
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
