# Generated by Django 5.0.6 on 2024-06-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelstester', '0009_remove_student_courses_remove_teacher_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
    ]
